export const BUSINESS_MINIMUM_AMOUNT_SWAP =
    import.meta.env.VITE_BUSINESS_MINIMUM_AMOUNT_SWAP || '50';
export const BUSINESS_MAXIMUM_AMOUNT_SWAP =
    import.meta.env.VITE_BUSINESS_MAXIMUM_AMOUNT_SWAP || '10000';
